services:
  app:
    build:
      context: ./docker/php/
      args:
        UID: 1000
        GID: 1000
    working_dir: /var/www/candle-grabber
    volumes: 
      - .:/var/www/candle-grabber
  db:
    iamge: mariadb
    container_name: candle-grabber-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
