services:
  app:
    build:
      context: ./docker/php/
      args:
        UID: 1000
        GID: 1000
    working_dir: /var/www/candle-grabber
    volumes: 
      - .:/var/www/candle-grabber
      - ./docker/php/configs/php-memory-limit.ini:/usr/local/etc/php/conf.d/php-memory-limit.ini

  db:
    image: mariadb
    container_name: candle-grabber-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - db-data:/var/lib/mysql
  db-test:
    image: mariadb
    container_name: candle-grabber-db-test
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3307:3306
    volumes:
      - ./docker/db/initdb_test.sql:/docker-entrypoint-initdb.d/initdb.sql
      - db-data-test:/var/lib/mysql
volumes:
  db-data:
  db-data-test:
